"""
Category color scheme. 
No functions defined, only a dictionary of category-to-color mappings.
"""
 
categories_and_colors = {'filesystem':'#ffe3c5',
    'registry':'#ffc5c5',
    'process':'#c5e0ff',
    'threading':'#d3e0ff',
    'services':'#ccc5ff',
    'device':'#d3c5cc',
    'network':'#d3ffc5',
    'socket':'#d3ffc5',
    'synchronization':'#f9c5ff',
    'browser':'#dfffdf',
    'crypto':'#f0f2c5',
    'system':'#fffcc5',
    'misc':'lightgrey',
    'hooking':'aqua',
    'windows':'blue',
    'com':'black',
    'others':'red',
    # Refactored classes - colors
    'Directory Management':'aqua',
    'Files and I/O (Local file system)':'bisque',
    'Disk Management':'blueviolet',
    'Volume Management':'brown',
    'Windows Shell':'burlywood',
    'Registry':'cadetblue',
    'Windows Internet (WinINet)':'chartreuse',
    'CNG Cryptographic Primitive':'chocolate',
    'Network Management':'coral',
    'Domain Name System (DNS)':'cornflowerblue',
    'Windows Sockets (Winsock)':'crimson',
    'Windows Networking (WNet)':'darkgoldenrod',
    'Synchronization':'darkgray',
    'Memory Management':'darkgreen',
    'Structured Exception Handling': 'darkorange',
    'Processes': 'darkorchid',
    'Time': 'darkred',
    'Debugging': 'darkseagreen',
    'Authorization': 'deeppink',
    'Dynamic-Link Libraries (DLLs)': 'fuchsia',
    'Handle and Objects': 'gold',
    'Services': 'goldenrod2',
    'Transactional NTFS': 'papayawhip', 
    'Software Licensing': 'tomato',
    'Device Management': 'turquoise1', 
    'Strings': 'sienna1',
    'System Information Functions': 'lime',
    'Mouse Input':'magenta', 
    'Conversion and Manipulation': 'olive',
    'Messages and Message Queues': 'pink',
    'Input Feedback Configuration':'tan',
    'Keyboard Input':'webgray',
    'Hooks':'mistyrose',
    'Resource':'khaki',
    'Cursors':'lavender',
    'Windows':'skyblue',
    'Atom':'lemonchiffon',
    'Pipes':'lightcoral',
    'Accessibility': '#0834f0',
    'Active Directory Service Interfaces (ADSI)': '#0a9470',
    'Application Recovery and Restart': '#099750',
    'Authentication': '#05eec0',
    'Backup': '#017bb0',
    'Bluetooth': '#06ebe0',
    'Buttons': '#01ae50',
    'COM': '#05bc20',
    'Cabinet API': '#08e620',
    'Carets': '#001950',
    'Client': '#012fc0',
    'Clipboard': '#0b1300',
    'Combo Boxes': '#0097e0',
    'Common Dialog Boxes': '#0964b0',
    'Communications Resources': '#07b660',
    'Compression API': '#0375f0',
    'Consoles': '#07e900',
    'Coordinate Space and Transformation': '#00ca80',
    'Core Audio': '#022ce0',
    'Cryptographic Next Generation (CNG)': '#062160',
    'Cryptography': '#004bf0',
    'Desktop Window Manager (DWM)': '#0ac710',
    'Developer License': '#0a4880',
    'Device Access': '#097e00',
    'Device Context': '#0ae060',
    'Dialog Boxes': '#089a30',
    'Direct2D': '#040dd0',
    'DirectComposition': '#0a2f30',
    'DirectShow': '#0686a0',
    'DirectWrite': '#0b45a0',
    'Driver Support': '#00fd20',
    'Drivers': '#0a15e0',
    'Dynamic Data Exchange (DDE)': '#000000',
    'Dynamic Data Exchange Management (DDEML)': '#0aadc0',
    'Edit Controls': '#006540',
    'Error Handling': '#0459c0',
    'Event Logging': '#04a5b0',
    'Event Tracing': '#06d290',
    'Extensible Authentication Protocol (EAP)': '#03a890',
    'Font and Text': '#04bf00',
    'GDI Print API': '#047310',
    'GDI+': '#00b130',
    'Get Connected Wizard': '#069ff0',
    'Group Policy': '#07cfb0',
    'Hardware Counter Profiling (HCP)': '#01e0f0',
    'IP Helper': '#048c60',
    'Icons': '#02ab70',
    'Internet Connection Sharing and Firewall': '#09c9f0',
    'Kernel Transaction Manager (KTM)': '#0b5ef0',
    'Keyboard Accelerators': '#081ba0',
    'Large Integer': '#03c1e0',
    'List Boxes': '#09fc90',
    'List-View Controls': '#029220',
    'Mailslots': '#03db30',
    'Menus': '#02de10',
    'Microsoft Management Console (MMC) 2.0': '#063ab0',
    'Microsoft Media Foundation': '#08ff70',
    'Mobile Broadband': '#007e90',
    'Monitor Configuration': '#0918c0',
    'Multicast Address Dynamic Client Allocation Protocol (MADCAP)': '#065400',
    'Multilingual User Interface (MUI)': '#0278d0',
    'Multiple Display Monitors': '#024630',
    'National Language Support (NLS)': '#0a7b20',
    'Native Wifi': '#05a2d0',
    'Network Access Protection (NAP)': '#080250',
    'Network Diagnostics Framework (NDF)': '#093210',
    'Network Dynamic Data Exchange (DDE)': '#032a00',
    'Network Policy Server Extensions (NPS)': '#066d50',
    'Network Share Management': '#0880e0',
    'OLE and Data Transfer': '#0783c0',
    'OpenGL': '#014910',
    'Operation Recorder': '#057030',
    'PROPVARIANT and VARIANT': '#06b940',
    'Painting and Drawing': '#034350',
    'Performance Counters': '#044070',
    'Power Management': '#0310b0',
    'Print Spooler': '#038f40',
    'Process Snapshotting': '#0556e0',
    'Process Status (PSAPI)': '#070530',
    'Property Sheets': '#075120',
    'Quality of Service (QOS)': '#086790',
    'Raw Input': '#03f480',
    'Restart Manager': '#050af0',
    'Rich Edit Controls': '#09b0a0',
    'Scroll Bars': '#0b2c50',
    'Server': '#09e340',
    'Simple Network Management Protocol (SNMP)': '#011670',
    'System Event Notification Service (SENS)': '#08b380',
    'TAPI': '#076a70',
    'TPM Base Services (TBS)': '#0a61d0',
    'Time Provider': '#071e80',
    'Timer': '#021390',
    'Toolbars': '#094b60',
    'Unicode and Character Set': '#016260',
    'Virtual Hard Disk (VHD)': '#042720',
    'Visual Styles': '#084e40',
    'Volume Shadow Copy': '#053d90',
    'Wait Chain Traversal': '#04f1a0',
    'WebDAV': '#01c7a0',
    'WebSocket Protocol Component': '#025f80',
    'Window Classes': '#0af9b0',
    'Window Properties': '#04d850',
    'Window Station and Desktop': '#019500',
    'Windows Connection Manager': '#02f760',
    'Windows Error Reporting (WER)': '#052440',
    'Windows Filtering Platform': '#02c4c0',
    'Windows Firewall with Advanced Security': '#060810',
    'Windows GDI': '#0737d0',
    'Windows Genuine Advantage': '#035ca0',
    'Windows Imaging Component (WIC)': '#01fa40',
    'Windows Media Format': '#079d10',
    'Windows Multimedia': '#08ccd0',
    'Windows Property System': '#058980',
    'Windows Resource Protection': '#00e3d0',
    'Windows Web Services': '#0032a0',
    'iSCSI Discovery Library API': '#05d570',
    'Misc':'#a9a9a9',
    'Browser':'#42d4f4',
    'unknown': '#FFFFFF'}
